storage:
  audio: "audio"
  images: "images"

solr:
  home: "solr"
  cores:
    default: "songs"
    songs: "songs"
    albums: "albums"
    artists: "artists"

spring.hateoas.use-hal-as-default-json-media-type: false